### ISSUE TITLE
A better answer about "How I rotate tick labels"

### ISSUE THREAD

**Issue by camel712** [matplotlib/cheatsheets#108]
The cheatsheets comment the method "`ax.set_[xy]ticks(rotation=90)`" to rotate ticks. However, it can cause confusion because the parameter "takes effect only if you pass labels"(official tutorial of `ax.set_[xy]ticks()`. So this is a incomplete form and not recommended.
As the official tutorial says, I suggest `ax.tick_params(axis='x', rotation=90)`.

**Comment by rougier** [comment]
Thanks for the report. Do you have a link to this part of the documentation?

**Comment by rougier** [comment]
@timhoffm Thanks for the explanation.
@camel712 Could you make a PR?
