### ISSUE TITLE
Make cheatsheet background non-transparent?

### ISSUE THREAD

**Issue by anntzer** [matplotlib/cheatsheets#110]
The handout thumbnails don't look very good on github's dark theme:
![s](https://user-images.githubusercontent.com/1322974/167252928-e9024d12-0ea7-4730-9f13-d3cebc3a3137.png)

**Comment by rougier** [comment]
Unless we use a dark theme for each and every graphic, I don't think a transparent background will fix the aesthetic on a dark background.

**Comment by anntzer** [comment]
I thought a solid white background would work decently in all cases?  (It's perhaps not optimal for dark backgrounds, but still better than the statu quo.)

**Comment by rougier** [comment]
Sorry, I read too fast. I thought you were requesting transparency everywhere. So yes, a non-transparent background would be much better.

**Comment by QuLogic** [comment]
Do you have any thoughts on making a dark themed cheatsheet? There does appear to be a way to auto-select the image depending on dark mode.

**Comment by rougier** [comment]
Since we have a style for the cheatsheet, it might be possible but some scripts will certainly needs adaptation. As for Latex, I guess it is possible. A good start would be to choose a dark palette (e.g. https://www.nordtheme.com/)

**Comment by timhoffm** [comment]
Is this getting off topic? IMHO cheat sheet theming is overkill. The original post was only stating that the thumbnails are partially transparent, which looks not great on a dark-themed GitHub. The easiest fix is to make the pngs for the preview pngs have a solid white background.
