### ISSUE TITLE
In the handout for beginners, plt.subplots(2, 1) should be used. 

### ISSUE THREAD

**Issue by radarFudan** [matplotlib/cheatsheets#117]
I'm using matplotlib-3.6.0.

When I use plt.subplots((2, 1)), there is an error: ValueError: Number of rows must be a positive integer, not (2, 1)

**Comment by jklymak** [comment]
Can you be more specific where this typo is on the cheat sheet?

**Comment by radarFudan** [comment]
It's at the third column of the handout for beginners. 

In the second code block of **Organize**.
`fig, (ax1, ax2) = plt.subplots((2,1))`

**Comment by rougier** [comment]
Thanks for the report. Can you make a PR?

**Comment by QuLogic** [comment]
Fixed by #118.
