### ISSUE TITLE
Cartopy version

### ISSUE THREAD

**Issue by StefRe** [matplotlib/cheatsheets#124]
@jimustafa what was the reason for pinning cartopy to `0.19.0.post1` in dbf92ab? It seems to work with any (newer) version too.

**Comment by ksunden** [comment]
I am pretty sure that almost all of the dependencies are hard pinned for the purpose of reproducibility... it is more like an "application" than a "library"

**Comment by jimustafa** [comment]
Hi @StefRe. Frankly, I do not recall exactly why `cartopy` was pinned to that specific version in dbf92ab. Generally speaking, and as @ksunden suggests, we are pinning versions for build reproduciblity. I see no reason not to upgrade `cartopy`; although, previously, there was an issue using later versions, as identified in https://github.com/matplotlib/cheatsheets/pull/74#issuecomment-930702071.

**Comment by rcomer** [comment]
Can the Ubuntu be updated to 22.04?  I believe that should take care of the proj 8+ problem:
https://packages.ubuntu.com/jammy/libproj-dev
