### ISSUE TITLE
markevery

### ISSUE THREAD

**Issue by SzymonGrabowski** [matplotlib/cheatsheets#133]
handout-intermediate.pdf, "Lines & markers"
Given X of length 1000, the plot with markevery=25 should mark 1000/25 = 40 points, but there are 20 of them on the figure, so it seems a bug to me. (If so, it matters also to the next example, in "Scales & projections").

**Comment by QuLogic** [comment]
The actual code appears to use `markevery=500`:
https://github.com/matplotlib/cheatsheets/blob/05fbbb90103b1c68f4922096b1e7290b7dac1a17/scripts/sine.py#L26-L36
Are you interested in putting a PR to fix this?
