### ISSUE TITLE
Update Beginner Cheatsheet: fig.show → plt.show

### ISSUE THREAD

**Issue by camriddell** [matplotlib/cheatsheets#134]
In the beginner handout, there is a brief section on how to display a given plot

https://github.com/matplotlib/cheatsheets/blob/05fbbb90103b1c68f4922096b1e7290b7dac1a17/handout-beginner.tex#L90-L95C9

I wanted to start a small discussion on whether the call to `fig.show()` should be replaced by `plt.show`.

Since this is a beginner cheatsheet, the management of a blocking GUI loop is slightly out-of-scope. `fig.show` does not manage this loop (whereas `plt.show` does), new users may wonder why their plot disappears as quickly as it appears when using `fig.show`.

**Comment by rougier** [comment]
I'm learning something here (I never  noticed the difference but probably because I'm only using `plt.show`). Where is it documented?

**Comment by timhoffm** [comment]
See the big warning box in https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.show

**Comment by rougier** [comment]
Thanks, it's quite visible actually. @camriddell Can yoiu make a PR?
