### ISSUE TITLE
Error from fonts.py: missing files

### ISSUE THREAD

**Issue by frankwwu** [matplotlib/cheatsheets#139]
Error: https://github.com/matplotlib/cheatsheets/blob/master/scripts/fonts.py
missing files:
"normal" : "../fonts/eb-garamond/EBGaramond08-Regular.otf",
"small-caps" : "../fonts/eb-garamond/EBGaramondSC08-Regular.otf"

**Comment by QuLogic** [comment]
Please read the instructions for building: https://github.com/matplotlib/cheatsheets#how-to-compile
