### ISSUE TITLE
Consistent capitalization of section titles

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/cheatsheets#18]
Capitalization of section titles switches between all words starting with capital letters and only the first word starting with a capital letter; e.g.

- Quick start
- Ten Simple Rules
- Ticks & labels
- Scales & Projections

Choose one way and stick with it throughout.

Note: The Matplotlib docs only capitalize the first word of a section. I don't care if the cheat sheets use the same rule, as long as they are consistent within themselves.

**Comment by rougier** [comment]
Right. Can you make a PR?
