### ISSUE TITLE
Missing ) in np.random.uniform

### ISSUE THREAD

**Issue by RMeli** [matplotlib/cheatsheets#20]
Thanks for the great cheatsheets! 

I think there is a missing `)` in
```
Z = np.random.uniform(0, 1, (8, 8)
```
under Matplotlib for Beginners/Choose (both `imshow` and `contourf`).

**Comment by rougier** [comment]
Well spotted, thanks. Can you make a PR?

**Comment by RMeli** [comment]
Sure, I'll provide a fix later today.
