### ISSUE TITLE
Legend placement

### ISSUE THREAD

**Issue by coandrei** [matplotlib/cheatsheets#25]
Thank you for the awesome work!

Am I miss something? ... to me the strings for A-F are incorrect. The bbox_to_anchor seems fine though.

![image](https://user-images.githubusercontent.com/14859034/86807609-af723380-c082-11ea-829a-b1657bc38ae8.png)

**Comment by coandrei** [comment]
Ok. Got it now. If it refers to the blue dot then still two things need to be fixed:
1) for D case ... x value should be positive .1 => bbox_to_anchor=(.1,-.1)
2) MatplotlibDeprecationWarning: Unrecognized location 'left'. Falling back on 'best'

**Comment by timhoffm** [comment]
Your observations are correct.

"right" is also only supported for backward compatibility and we should use "center right" for consistency.
https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.legend.html

@coandrei Do you want to provide a pull request with the changes?

**Comment by rougier** [comment]
@coandrei  a PR would be nice. Also for the numerical value, we should use {\ttfamily (0.1,0.1)} instead of (0.1,0.1). It will makes thing more readable.

**Comment by coandrei** [comment]
@rougier copy that.

**Comment by coandrei** [comment]
@rougier PR sent. I close this issue now.
