### ISSUE TITLE
cheatsheets-2.png shows interpolation different for none vs None

### ISSUE THREAD

**Issue by zingale** [matplotlib/cheatsheets#28]
If you look at the imagine cheatsheets-2.png linked in the README.md:
https://github.com/matplotlib/cheatsheets/blob/master/cheatsheets-2.png

in the interpolations image grid, the "none" version actually is using some sort of interpolation.  This makes it seem like `"none"` and `None` are different, but they should not be.

When I run the `interpolations.py` script locally 
(https://github.com/matplotlib/cheatsheets/blob/master/scripts/interpolations.py) I get the following:

[interpolations.pdf](https://github.com/matplotlib/cheatsheets/files/4886186/interpolations.pdf)

which has the correct top row.

The image in the repo should be updated.

**Comment by jklymak** [comment]
I think the difference is between PDF viewers and how they interpolate.  For instance, your PDF on Preview looks like the png:

<img width="483" alt="interps" src="https://user-images.githubusercontent.com/1562854/86823952-58e50500-c042-11ea-8991-f3509b2575e5.png">

I'm not sure what to do in this case - 'none' means just do whatever your renderer does.  Its generally a bad idea to use 'none'.  
`None` will do "Hanning" if the image is downsampled or upsampled less than 2 times, or `Nearest` if not (as of 3.2: https://github.com/matplotlib/matplotlib/pull/13724).  

Indeed, I think it would be useful if this cheatsheet used the new default "antialiased" at some point, though this is a grossly over-sampled image so the anti-aliasing doesn't kick in.

**Comment by QuLogic** [comment]
Relatedly, I think it showing None and none is confusing... The first is the special value, but the second is a string.

**Comment by rougier** [comment]
I would be annoying to remove the none (just because with it, I can have a 3x6 grids). But I agree it might be confusing. We either put it first without label but using the  "None" intepolation to suggest these are the real values.

**Comment by tacaswell** [comment]
Maybe put quotes on the strings?

**Comment by rougier** [comment]
Yes, we can add quotes. But still, the "none" does not seem to be really consistent across viewers. Is it worth to mention it?

**Comment by tacaswell** [comment]
I am :+1: on dropping 'none' (which is the same as 'nearest' in Agg, but leaves you at the mercy of your display program on the vector out puts) is reasonable.  There are other interpolations that we can pull from to still have a 3x3 grid.

**Comment by zingale** [comment]
either mentioning that "none" is not consistent or removing it would be good.

**Comment by jimustafa** [comment]
Might have been closed by #80. @timhoffm, please consider.
