### ISSUE TITLE
We need a license

### ISSUE THREAD

**Issue by rougier** [matplotlib/cheatsheets#3]
BSD ?

**Comment by mpetroff** [comment]
I don't think this was properly resolved. The cheat sheets all say that they are under a CC BY 4.0 International license, but the `LICENSE.txt` file is a BSD 2-Clause license. These should match. Either the cheat sheets need to be changed, or the `LICENSE.txt` file does.

**Comment by rougier** [comment]
The produced documents are CC-BY but the sources are BSD-2.

**Comment by mpetroff** [comment]
This should be clarified in the readme, then. In the current form, it looks like an oversight, not something intentional.
