### ISSUE TITLE
Missing closing parenthesis in beginners handout

### ISSUE THREAD

**Issue by pierrepo** [matplotlib/cheatsheets#41]
I think some closing parenthesis are missing in the beginners handout:
https://raw.githubusercontent.com/matplotlib/cheatsheets/master/handout-beginner.png

When `np.random.uniform()` is used with the size argument as a tuple, the last closing parenthesis is missing.

Here:
![image](https://user-images.githubusercontent.com/733861/91154750-2bbbe700-e6c2-11ea-9bd2-73d1a6cd3eeb.png)

and here:
![image](https://user-images.githubusercontent.com/733861/91154840-4beba600-e6c2-11ea-81e3-5020a6279bef.png)

**Comment by rougier** [comment]
Oh thanks for the report. Can you make a PR or do you prefer I correct them directly ?

**Comment by jimustafa** [comment]
This was fixed in #23 to close #20. It seems that the handouts were not updated after the fix, which probably led to #41. With #69, the up-to-date (fixed) beginners handout should show up in the `README`. This issue could probably be closed.
