### ISSUE TITLE
Typo in handouts tips

### ISSUE THREAD

**Issue by LouisJustinTALLOT** [matplotlib/cheatsheets#45]
In the last paragraph we read `documenation` instead of `documentation`...

**Comment by LouisJustinTALLOT** [comment]
![image](https://user-images.githubusercontent.com/72044417/102093734-cc751480-3e21-11eb-87b1-c8b86e5645c7.png)
There are in fact multiple typos in this paragraph...

**Comment by rougier** [comment]
Thanks. I need to rebuild all the sheets once everything has been merged. Sorry for being very late on that.
