### ISSUE TITLE
A Suggestion about CI/CD.

### ISSUE THREAD

**Issue by lartpang** [matplotlib/cheatsheets#52]
Perhaps, we can use the GitHub Action or other CI/CD tools to automatically compile and release these beautiful and useful files.

**Comment by rougier** [comment]
That was the initial plan but I did not have time to look at it and I'm not so familiar with GA. Any help help much appreciated. It's only a matter of rebuilding all the figures and the latex documents. And we need to check if the results has the right number of page to detect any faulty output.
