### ISSUE TITLE
add candlestick cheat .

### ISSUE THREAD

**Issue by mablue** [matplotlib/cheatsheets#62]
the most important thing on charting is finansal charts that matplotlib didnt work around it.
yes it have some libs and things but not sharply have do something for that.
please add cheatsheat for finansal and candlistic charts to help us thanks

**Comment by story645** [comment]
Hi, that's something the @matplotlib/mpl-finance team might be interested in doing, but is out of scope for these cheatsheets.

**Comment by mablue** [comment]
thanks for your support . I send this issue to a wrong place cuz of reaching my voice to core programmers and someone who undrestands the options of matplotlib to commit and add some raw option to doing that smple thing.sorry if its not good place for saying that but we need help of you .and matplotlib now didnt usable for bunch of people that use ploting finanssal charts.I dont know why a big and very strong python ploting lib cant make a candle shape.that can usefull for meny meny people .

**Comment by story645** [comment]
Candlestick plots are implemented in https://github.com/matplotlib/mplfinance rather than in matplotlib because the matplotlib team does not have core devs who understand finance plots well. On the other hand, the mplfinance team consists of developers who understand financial plots very well.

**Comment by DanielGoldfarb** [comment]
@mablue 
Masoud,
If you will please read though the [**mplfinance basic usage**](https://github.com/matplotlib/mplfinance#basic-usage) as well as the [other **mplfinance tutorials**](https://github.com/matplotlib/mplfinance#contents-and-tutorials), and then perhaps suggest here which features you think would be most useful to include on a cheetsheet (I have my own ideas which ones, but want to hear from users) then I will consider making such a cheetsheet.

As stated above, although mplfinance is under the matplotlib organization, it is a separate package.  It is kept as a separate package primarily for two reasons: (1) mplfinance has a strong dependency on pandas (and we would like to avoid matplotlib having a dependency on pandas), and (2) most of the matplotlib developers do not have the financial background that is helpful in guiding the direction of mplfinance developement.

Thank you very much for raising this issue.  It's a good idea!   All the best.  --Daniel

**Comment by mablue** [comment]
@story645 thank you very much I check the link and yes Im shock its very simple way to do with mpl.
@DanielGoldfarb thanks for your support.I just over shoked and get heart attack when I chaked whole matplotlib cheatsheat and didnt see Candlestick chart optionality.Its very amazing for me cuz the much using chart on the world(I think) is Candlestick charts.instade of that bunch of very advance charts that implemented inside of matplotlib its our right to have one candle that can burn without using any other implementin or etc!
maybe yes there is on mplfinance repo we can reach more good suport and other amazing things.but cuz of importance of candlestick charts for humanity its a wrong way.(I think)
It looks like we designed a fulloption futuristic car with four full-option wheels. But instead of installing it on the car, we sell them to the user as a separate package.and the buyer get heart attack when see the options of car and also see that it not have wheels as well:))

**Comment by DanielGoldfarb** [comment]
@mablue 
I will try to make up a **candlestick cheatsheet** sometime in the next few weeks.

In the meantime regarding candlestick width as an expression of time, this is not supported yet, but there is [a request for it here](https://github.com/matplotlib/mplfinance/issues/398).

I know you would like to see candlesticks built into matplotlib itself, but I think you will find, [**if you take some time to work through these tutorials**](https://github.com/matplotlib/mplfinance#contents-and-tutorials) that the mplfinance makes it much easier to generate candlesticks compared with using the lower level matplotlib methods.
