### ISSUE TITLE
tight_layout is a method of plt, not ax

### ISSUE THREAD

**Issue by mathiasbockwoldt** [matplotlib/cheatsheets#67]
https://github.com/matplotlib/cheatsheets/blob/af1506599facc885ce17a8c72601c1192986450a/cheatsheets.tex#L721

This should become `plt.\textbf{tight\_layout}()\\`

**Comment by QuLogic** [comment]
It's also a Figure method, so should probably be `fig.tight_layout()`; would you like to open a PR with the fix?
