### ISSUE TITLE
Style the website

### ISSUE THREAD

**Issue by Sriram-bb63** [matplotlib/cheatsheets#82]
Website: https://matplotlib.org/cheatsheets/

The website is currently contains only plain HTML.
It would be better if we can make it look more like the official site: https://matplotlib.org/stable/index.html

**Comment by jklymak** [comment]
We now have mpl-sphinx-theme for that.

**Comment by QuLogic** [comment]
Probably will help, but the page here is just a single static file, not a Sphinx build.

**Comment by jklymak** [comment]
As is the brochure site, so a minor re-architecture to make it a Sphinx site is to just wrap the raw html body in an rst stub that inputs the html.
