### ISSUE TITLE
broken links on cheatsheets site

### ISSUE THREAD

**Issue by jimustafa** [matplotlib/cheatsheets#89]
There are a couple of broken links in the navigation bar for the cheatsheets site https://matplotlib.org/cheatsheets, specifically the "Plot types" and "Release notes" links. Once current matplotlib dev version is released and the docs are published to https://matplotlib.org/stable, this would not be an issue; still, probably should be addressed.

Also, the search bar is a bit unnecessary, as it does not search the main site. Can the sidebar from the main site be integrated into the cheatsheets site. Or, maybe it is better to build the cheatsheets site in the matplotlib docs.

**Comment by jklymak** [comment]
Matplotlib won't link the site until the new docs are published.    

The sidebar is configurable, as per pydata- sphinx-theme
